give @a parv:copper_dust 64
give @a parv:cmeter 1
give @a parv:c_wire_0 64
give @a parv:c_wire_1 64
give @a parv:c_wire_2 64
give @a parv:c_wire_3 64
give @a parv:c_wire_4 64
give @a parv:copper_pillar 64
give @a parv:exposed_pillar 64
give @a parv:weathered_pillar 64
give @a parv:oxidized_pillar 64
give @a parv:waxed_copper_pillar 64
give @a parv:waxed_exposed_pillar 64
give @a parv:waxed_weathered_pillar 64
give @a parv:waxed_oxidized_pillar 64