give @a parv:copper_dust 64
give @a parv:cmeter 1
give @a parv:battery 64
give @a parv:wire10dup 64
give @a parv:scaffolder 64
give @a parv:copper_bars 64
give @a parv:cepeater 64
give @a parv:wire10 64
give @a parv:batterydup 64