give @p parv:shifter 64
give @p parv:chonker 64
give @p parv:shielder 64
give @p parv:sprinter 64
give @p parv:jumper 64
give @p parv:firer 64
give @p parv:swimmer 64
give @p parv:sleeper 64
give @p repeater 64
give @p comparator 64